CREATE TABLE IF NOT EXISTS USER_INFO (
    ID INT NOT NULL AUTO_INCREMENT,
    USER_EMAIL VARCHAR(255) NOT NULL,
    USER_NICKNAME VARCHAR(255) NOT NULL,
    USER_PW VARCHAR(256) NOT NULL,
    USER_NAME VARCHAR(255) NOT NULL,
    USER_PHONE_NUMBER VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS CERTIFICATE_INFO (
    ID INT NOT NULL AUTO_INCREMENT,
    PHONE_NUMBER VARCHAR(30) NOT NULL,  
    CERTIFICATE_NUMBER VARCHAR(10) NOT NULL,
    CREATED TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);